---
title: "ProjectSample"
date: '2022-10-13'
output: pdf_document
---
```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(lubridate)
library(tidyr)
library(usmap)
library(reshape2)
```

```{r}
shootingsDFOrig <- read.csv("shootings.csv", as.is = T)
```

```{r}
shootingsDF <- select(shootingsDFOrig, c("case", "location", "date", "fatalities", "injured", "total_victims", "location1", "age_of_shooter", "prior_signs_mental_health_issues", "weapons_obtained_legallY", "weapon_type", "race", "gender", "type", "year"))
```

```{r}
columns <- c("location1", "prior_signs_mental_health_issues", "weapons_obtained_legallY", "weapon_type", "race", "gender", "type")
shootingsDF[, columns] <- lapply(shootingsDF[, columns], factor)
```

```{r}
colnames(shootingsDF) <- c("Name", "Location", "Date", "Fatalities", "Injured", "TotalVictims", "LocationType", "AgeOfShooter", "PriorMH", "ObtainedLegally", "WeaponType", "Race", "Gender", "ShootingType", "Year")
```


```{r}
shootingsDF$Date <- format(mdy(shootingsDF$Date), "%m-%d-%Y")
#shootingsDF$Date <- as.POSIXct(shootingsDF$Date , format = "%m-%d-%Y")
```

```{r message=FALSE, warning=FALSE}
shootingsDF$Injured <- as.integer(shootingsDF$Injured)
shootingsDF$TotalVictims <- as.integer(shootingsDF$TotalVictims)
shootingsDF$AgeOfShooter <- as.integer(shootingsDF$AgeOfShooter)
```

```{r}
summary(shootingsDF)
```

```{r message=FALSE, warning=FALSE}
ggplot(shootingsDF, aes(x = AgeOfShooter)) + 
  geom_histogram(color="#1A237E", fill="#4FC3F7", alpha = 0.6, binwidth = 12, size = 1) + 
  labs(title = "Histogram showing the Age Range of the Shooters", x = "Age", y = "Frequency") +
  theme_classic()
```

```{r}
shooterRace <- data.frame(table(shootingsDF$Race))
colnames(shooterRace) <- c("Race","Frequency")

ggplot(shooterRace, aes(x = reorder(Race, Frequency),y = Frequency, fill = Race)) + 
  geom_bar(stat = "identity", width = 0.9) + 
  theme_void() +
  geom_text(aes(label = Frequency)) +
  coord_polar(theta = "y") +
  labs(title = "Race of the Shooters in Relative Proportion to each other")
```

```{r message=FALSE, warning=FALSE}
shooterRaceGen <- data.frame(table(shootingsDF$Race, shootingsDF$Gender))
colnames(shooterRaceGen) <- c("Race","Gender", "Frequency")

ggplot(shooterRaceGen, aes(x = reorder(Race, -Frequency), y  = Frequency, fill = Gender)) + 
  geom_bar(stat = "identity", position = "fill") +
  geom_bar(stat = "identity", color = "black", size = 0.3, show.legend = FALSE, position = "fill") +
  theme_classic() +
  labs(title = "Relation between Race and Gender", x = "Race", y = "Proportionate Frequency") 
```


```{r}
dateSep <- separate(shootingsDF, "Date", c("Month","Day","Year"), sep = "-")

yearTS <- dateSep %>% 
  select(Year) %>% 
  group_by(Year) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

ggplot(yearTS, aes(x = Year, y = count, group = 1)) +
  geom_line(color = "red", size = 1) + 
  geom_point(color = "black", size = 1.5) +
  theme_classic() + 
  theme(legend.position = "none", axis.text.x = element_text(angle = 90)) + 
  labs(x = "Years", y = "Aggregate Number of Incidents",title = "Number of Incidents by Year")
```

```{r message=FALSE, warning=FALSE}

longLatDF <- data.frame(select(shootingsDFOrig, c("longitude", "latitude", "fatalities")))
colnames(longLatDF) <- c("lon", "lat", "fatalities")
usMapTra <- usmap_transform(longLatDF)

plot_usmap(labels = TRUE, theme = theme_void()) + 
  coord_fixed(1.3) +
  scale_colour_gradient(low = "cyan1", high = "blue") +
  geom_point(data = usMapTra, aes(x = x, y = y, size = fatalities, color = fatalities), alpha = 0.7) +
  scale_size_continuous(range = c(0, 20)) +
  theme(legend.position = "right", axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.key.size = unit(1, 'cm')) +
  labs(title = "Shooting Locations", subtitle = "Points size relative to Number of Fatalities") +
  guides(size = guide_legend(title = "Fatalities", override.aes = list(size = 8)), color = guide_legend(title = "Fatalities", override.aes = list(size = 8)))
```

```{r}
stateSep <- separate(shootingsDF, "Location", c("City","State"), sep = ", ")
stateCnt <- data.frame(table(stateSep$State))
colnames(stateCnt) <- c("State", "Frequency")

stateCnt <- stateCnt %>%
  arrange(desc(Frequency))

stateCnt <- head(stateCnt, 10)

ggplot(stateCnt, aes(x = reorder(State, -Frequency), y = Frequency, fill = State)) + 
  geom_bar(stat = "identity", width = 0.9, show.legend = FALSE) + 
  geom_label(aes(label = Frequency, hjust = 1.2), show.legend = FALSE) +
  labs(title = "Top 10 States with Highest Shooting Count", x = "State", y = "Shooting Count") +
  theme_classic() +
  coord_flip() 
```

```{r}
weaponTypeDF <- data.frame(table(shootingsDF$WeaponType))
colnames(weaponTypeDF) <- c("WeaponType", "Frequency")

weaponTypeDF <- weaponTypeDF %>% 
  arrange(desc(WeaponType)) %>%
  mutate(prop = Frequency / sum(weaponTypeDF$Frequency) * 1) %>%
  mutate(ypos = cumsum(prop)- 0.5 * prop) %>%
  arrange(prop) %>%
  mutate(labels = scales::percent(prop))

ggplot(weaponTypeDF, aes(x = "", y = prop, fill = WeaponType)) +
  geom_bar(stat = "identity", width = 1,  color = "white")+
  coord_polar("y", start = 0) + 
  geom_text(aes(y = ypos, label = labels), color = "black", size=3.5) +
  theme_void() +
  labs(title = "Distrbution of Weapon Types") 
```

```{r}
locDF <- data.frame(table(shootingsDF$LocationType))
colnames(locDF) <- c("LocationType", "Frequency")

locDF <- locDF %>% 
  arrange(desc(LocationType)) %>%
  mutate(prop = Frequency / sum(locDF$Frequency) * 1) %>%
  mutate(ypos = cumsum(prop)- 0.5 * prop) %>%
  arrange(prop) %>%
  mutate(labels = scales::percent(prop))

ggplot(locDF, aes(x = 2, y = prop, fill = LocationType)) +
  geom_bar(stat = "identity")+
  xlim(.2,2.5) +
  coord_polar("y", start = 0) + 
  geom_text(aes(y = ypos, label = labels), color = "black", size=5) +
  theme_void() + 
  labs(title = "Distrbution of Shooting Location Types") 
```

```{r}
obLDF <- data.frame(table(shootingsDF$ObtainedLegally))
colnames(obLDF) <- c("ObtainedLegally", "Frequency")

obLDF <- obLDF %>% 
  arrange(desc(ObtainedLegally)) %>%
  mutate(prop = Frequency / sum(obLDF$Frequency) * 1) %>%
  mutate(ypos = cumsum(prop)- 0.5 * prop) %>%
  arrange(prop) %>%
  mutate(labels = scales::percent(prop))

ggplot(obLDF, aes(x = "", y = prop, fill = ObtainedLegally)) +
  geom_bar(stat = "identity", width = 1,  color = "white")+
  coord_polar("y", start = 0) + 
  geom_text(aes(y = ypos, label = labels), color = "black", size=3.5) +
  theme_void() + 
  labs(title = "Percentage of Weapons Obtained Legally") 
```

```{r}
shooterRaceGen <- data.frame(table(shootingsDF$ObtainedLegally, shootingsDF$PriorMH))
colnames(shooterRaceGen) <- c("ObtainedLegally","PriorMH", "Frequency")

ggplot(shooterRaceGen, aes(x = reorder(ObtainedLegally, -Frequency), y  = Frequency, fill = PriorMH)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_bar(stat = "identity", color = "black", size = 0.3, show.legend = FALSE, position = position_dodge()) +
  theme_classic() +
  labs(title = "Relation between Prior Signs of Mental Health Issues and Weapons Obtained Legally", x = "Weapons Obtained Legally", y = "Frequency") +
  guides(fill = guide_legend(title = "Prior Signs of MH Issues"))
```

```{r}
shooterRaceGen <- data.frame(table(shootingsDF$ObtainedLegally, shootingsDF$WeaponType))
colnames(shooterRaceGen) <- c("ObtainedLegally","WeaponType", "Frequency")

ggplot(shooterRaceGen, aes(x = reorder(ObtainedLegally, -Frequency), y  = Frequency, fill = WeaponType)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_bar(stat = "identity", color = "black", size = 0.3, show.legend = FALSE, position = position_dodge()) +
  theme_classic() +
  labs(title = "Relation between Weapon Type and Weapon Obtained Legally", x = "Weapons Obtained Legally", y = "Frequency") +
  guides(fill = guide_legend(title = "Weapon Type"))
```

```{r warning=FALSE}
locVicDF <- shootingsDF  %>% 
  select(LocationType, TotalVictims)     %>% 
  group_by(LocationType)  %>% 
  summarize(tot_vic = sum(TotalVictims)) 

ggplot(locVicDF, aes(x = reorder(LocationType, -tot_vic), y  = tot_vic, fill = LocationType)) +
  geom_bar(stat = "identity", show.legend = FALSE,) +
  geom_label(aes(label = tot_vic), show.legend = FALSE, size = 3) +
  theme_classic() +
  labs(title = "Total Victim Count based on Shooting Location Type", x = "Location Type", y = "Total Victim Count") 
```

```{r}
MHGen <- data.frame(table(shootingsDF$PriorMH, shootingsDF$Gender))
colnames(MHGen) <- c("PriorMH","Gender", "Frequency")

ggplot(MHGen, aes(x = reorder(Gender, -Frequency), y  = Frequency, fill = PriorMH)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_bar(stat = "identity", color = "black", size = 0.3, show.legend = FALSE, position = position_dodge()) +
  theme_classic() +
  labs(title = "Relation between Prior Signs of Mental Health Issues and Gender", x = "Gender Category", y = "Frequency") +
  guides(fill = guide_legend(title = "Prior Signs of MH Issues"))
```

```{r}
locFIDF <- melt(shootingsDF[, c('LocationType','Fatalities','Injured')], id.vars = 1)

ggplot(locFIDF, aes(x = LocationType, y = value)) + 
  geom_bar(aes(fill = variable),stat = "identity",position = "dodge") +
  theme_classic() + 
  labs(title = "Injured vs Fatality", x = "Shooting Location Type", y = "Frequency") +
  guides(fill = guide_legend(title = "Type"))
```

```{r}
nameCnt  <-shootingsDF %>%
  select(Name, TotalVictims) %>% 
  arrange(desc(TotalVictims)) %>% 
  head(10)

ggplot(nameCnt, aes(reorder((factor(Name, level = Name)), -TotalVictims), TotalVictims, fill = Name))+
  geom_bar(stat="identity")+
  theme_classic() +
  labs(x = "Event Name",y = "Total Victims", title = "Maximum victims for an Event")+
  theme(legend.position="none", axis.text.x = element_text(angle = 90))+
  geom_text(aes(label = TotalVictims, hjust = 1.2), show.legend = FALSE) +
  coord_flip() 
```

